const ORDER_STATUS = {
    ALL: "ALL",
    PENDING: "PENDING",
    APPROVED: "APPROVED",
    DELIVERING: "DELIVERING",
    DELIVERED: "DELIVERED",
    CANCELED: "CANCELED",
};

export default ORDER_STATUS;

