const ADDRESS_ACTIONS = {

    // Lấy danh sách địa chỉ
    ADDRESS_LIST_REQUEST: "ADDRESS_LIST_REQUEST",
    ADDRESS_LIST_SUCCESS: "ADDRESS_LIST_SUCCESS",
    ADDRESS_LIST_FAIL: "ADDRESS_LIST_FAIL",

    // Tạo địa chỉ
    ADDRESS_CREATE_REQUEST: "ADDRESS_CREATE_REQUEST",
    ADDRESS_CREATE_SUCCESS: "ADDRESS_CREATE_SUCCESS",
    ADDRESS_CREATE_FAIL: "ADDRESS_CREATE_FAIL",

    // Chỉnh sửa địa chỉ
    ADDRESS_EDIT_REQUEST: "ADDRESS_EDIT_REQUEST",
    ADDRESS_EDIT_SUCCESS: "ADDRESS_EDIT_SUCCESS",
    ADDRESS_EDIT_FAIL: "ADDRESS_EDIT_FAIL",

    // Xóa địa chỉ
    ADDRESS_DELETE_REQUEST: "ADDRESS_DELETE_REQUEST",
    ADDRESS_DELETE_SUCCESS: "ADDRESS_DELETE_SUCCESS",
    ADDRESS_DELETE_FAIL: "ADDRESS_DELETE_FAIL",

    // Đặt địa chỉ mặc định
    ADDRESS_SET_DEFAULT_REQUEST: "ADDRESS_SET_DEFAULT_REQUEST",
    ADDRESS_SET_DEFAULT_SUCCESS: "ADDRESS_SET_DEFAULT_SUCCESS",
    ADDRESS_SET_DEFAULT_FAIL: "ADDRESS_SET_DEFAULT_FAIL"
};

export { ADDRESS_ACTIONS };
